// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ0nKDQOrQFpII_wQr5r6HhO9rlZfPhFE',
    appId: '1:985825165679:web:20f4ce76e0ddacf133a89a',
    messagingSenderId: '985825165679',
    projectId: 'checkpoint-attendance-2025',
    authDomain: 'checkpoint-attendance-2025.firebaseapp.com',
    storageBucket: 'checkpoint-attendance-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:985825165679:android:ed726b7d2adea4a433a89a',
    messagingSenderId: '985825165679',
    projectId: 'checkpoint-attendance-2025',
    storageBucket: 'checkpoint-attendance-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcwKfBdcunalo6QXZRCuhJqoH5evcenOY',
    appId: '1:985825165679:ios:4555e48ecf6a6f1a33a89a',
    messagingSenderId: '985825165679',
    projectId: 'checkpoint-attendance-2025',
    storageBucket: 'checkpoint-attendance-2025.firebasestorage.app',
    iosBundleId: 'com.example.hbap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcwKfBdcunalo6QXZRCuhJqoH5evcenOY',
    appId: '1:985825165679:ios:4555e48ecf6a6f1a33a89a',
    messagingSenderId: '985825165679',
    projectId: 'checkpoint-attendance-2025',
    storageBucket: 'checkpoint-attendance-2025.firebasestorage.app',
    iosBundleId: 'com.example.hbap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ0nKDQOrQFpII_wQr5r6HhO9rlZfPhFE',
    appId: '1:985825165679:web:f252df93aadd151a33a89a',
    messagingSenderId: '985825165679',
    projectId: 'checkpoint-attendance-2025',
    authDomain: 'checkpoint-attendance-2025.firebaseapp.com',
    storageBucket: 'checkpoint-attendance-2025.firebasestorage.app',
  );

}